package kamkeel.hextext.api.rendering;

import java.util.List;
import java.util.Map;

/**
 * Represents the sanitized text and associated render directives generated by HexText's preprocessing pipeline.
 */
public interface RenderPlan {

    /**
     * Returns {@code true} when the caller should replace their source text with {@link #getDisplayText()} prior to
     * rendering.
     */
    boolean shouldReplaceText();

    /**
     * Returns the sanitized text that should be sent to the font renderer when {@link #shouldReplaceText()} is
     * {@code true}. May be {@code null} when no replacement is required.
     */
    String getDisplayText();

    /**
     * Returns the map of deferred directives keyed by the character index in {@link #getDisplayText()} at which they
     * should execute.
     */
    Map<Integer, List<RenderDirective>> getInstructions();

    /**
     * Convenience method that returns {@code true} when the result contains any render directives.
     */
    boolean hasInstructions();
}
